#pragma config(Sensor, S1,     light,          sensorEV3_Color)
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     ultra,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          Right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SPEED 30
#define ROW 7
#define COL 9
#define TICK 206

int map[ROW][COL];

//Prototypes
void forward_square();
void turnLeft();
void turnRight();
void init();
int get_threshold();
int forward(int threshold);
void backwards();
void grid_pass();
void file_write();
void file_write2(int c1,int c2, int color);

task main()
{
	
	
	int beginsq = 2;
	int object = 3;
	
	int j;
	int squares;
	int t_hold=get_threshold();
	int r_object=0, c_object=0,color=0;
	//Makes all the values on the map 0
	init();
	//Goes until the double line
	turnLeft();
	squares=forward(t_hold);
	map[squares][0]=beginsq;
	backwards();

	//Goes around the grid
	turnRight();
	grid_pass();

	//Return home
	turnRight();
	turnRight();
	for(j=COL-1;j>-1;j--)
		forward_square();
	turnRight();
	repeat(ROW-squares+1)
	{
		forward_square();
	}

	//write on file
	file_write();
	file_write2(r_object,c_object,color);
}//END MAIN

//Passes through the grid
void grid_pass()
{
	int j,i;
	int black = 1;
	for(i=0;i<ROW;i++)
	{
		if(i%2==0)
		{
			for(j=0;j<COL;j++)
			{	
				clearTimer(T1);
				forward_square();
				if(SensorValue(light) < threshold && time2[T2]<700)
					map[i][j]=black;
			}
			if(i!=6)
			{
				turnRight();
				forward_square();
				turnRight();
			}
		}
		else
		{
			for(j=COL-1;j>-1;j--)
			{	
				clearTimer(T1);
				forward_square();
				if(SensorValue(light) < threshold && time2[T2]<700)
					map[i][j]=black;
			}
			turnLeft();
			forward_square();
			turnLeft();
		}
	}//end for
}

//Function to move by 1 square
void forward_square()
{
	while(getMotorEncoder(Left)<360)
	{
		motor[motorA]=SPEED;
 		motor[motorD]=SPEED;
 	}
}

//Turns left 90 degrees
void turnLeft()
{
	setMotorSyncTime(Left,Right,-100,705,25);
	sleep(705);
}


//Turns right 90 degrees
void turnRight()
{
	setMotorSyncTime(Left,Right,100,705,25);
	sleep(740);
}

//Function to move forward until the double line
int forward(int threshold)
{
	int last_seen=1;
	int squares=0, lines=0;
	/*
	Squares counts the squares i traveled until the double line
	Line counts for the double line.
	*/
	clearTimer(T1);

	while(lines<2)
	{
		if(time1[T1]>300)
		{
			clearTimer(T1);
			lines=0;
		}
		motor[motorA]=SPEED;
 		motor[motorD]=SPEED;
		//Line count
		if (SensorValue(light) < threshold)
 	  {

 			 if (last_seen == 1)
 			 {
 			  	lines++;
 			  	squares++;
 				  last_seen = 0;
 			 }
 		}
 		else  last_seen = 1;
 	}

 	/*
 	Squares -2 because it will
 	count the 2 lines for grid ending
 	*/
 	return (squares-2);
}


//Function to get the room lighting
int get_threshold()
{
	int max, min, mid;
/*
If touch sensor is not
pressed, it returns 0, else returns 1
*/
	while(SensorValue(touch) == 0)
	{
		displayBigStringAt(0,15,"Get the black value");
		max = SensorValue(light);
	}


	while(SensorValue(touch) == 0)
	{
		displayBigStringAt(0,15,"Get the white value");
		min = SensorValue(light);
	}

	mid = (max + min)/2;

	return mid;
}

/*
function to write
the coordinates of the object and it's
square color
*/
void file_write2(int c1,int c2, int color)
{
	long fp;

	string File = "ObjectInfo";   //File name

	// Open the file for writing and return a handle,

	fp = fileOpenWrite(File);

	fileWriteData(fp, "Object coordinates\n",20);
	//Not working, need another function
	/*fileWriteData(fp, (string)c1, 2);
	fileWriteData(fp, (string)c2, 2);*/
	if(color==0)
		fileWriteData(fp, "White",6);
	else
		fileWriteData(fp, "Black",6);
	//File Close
	fileClose(fp);
}

/*
Function to write to file
a is the map
*/
void file_write()
{
 	int i,j;
	long  fp;

	string File = "projectMAP";   //File name

	// Open the file for writing and return a handle,

	fp = fileOpenWrite(File);
	for(i=0;i<ROW;i++)
	{
		for(j=0;j<COL;j++)
		{
			//Not working, need another function
			/*fileWriteData(fp, (string)map[i][j]), 2);
			fileWriteData(fp, " ", 2);*/
		}
		fileWriteData(fp, "\n", 2);
	}


	//File Close
	fileClose(fp);
}

//Function to initialize the map
void init()
{
	int i,j;
	for(i=0;i<ROW;i++)
	{
		for(j=0;j<COL;j++)
		{
			map[i][j]=0;
		}
	}
}

//Function to move backwards once the double line is found
void backwards()
{
	motor[motorA]=-SPEED;
	motor[motorD]=-SPEED;
	wait1Msec(300);
}


