#pragma config(Sensor, S2,     BumpMe,         sensorEV3_Touch)
#pragma config(Motor,  motorA,          Left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          Right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward2(int speed)
{
	while(SensorValue(BumpMe) == 0)
	{
		setMotorSyncTime(Left, Right, 0, 0, speed);
	}
}

void t_left()
{
	motor[Right] = 50;			//Set the leftMotor (motor1) to half power forward (50)
	motor[Left] = -50;  	//Set the rightMotor (motor4) to half power forward (50)
	sleep(400);
}
void rev()
{
	motor[Right] = -50;
	motor[Left] = -50;
	sleep(1000);
}

task main()
{
	int battery=getBatteryVoltage();
	int r=-1;
	while(r<0)
		r=rand()%100 +1;


	displayBigTextLine(4,"Speed: %d",r);
	displayBigTextLine(6,"Battery: %d",battery);
	sleep(1000);


	forward2(r);
	rev();

	/*setMotorSyncTime(motorA, motorD, 0, 1000, r);
	sleep(1000);*/
}
