
#pragma config(Motor,  motorA,          LeftMotor,     tmotorEV3_Medium, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          RightMotor,    tmotorEV3_Medium, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  int min = -100;   // create int variable 'min' and set it to -100
  int max = 100;    // create int variable 'max' and set it to 100

  srand(nSysTime);  // generate seed for rand() from current system time

  while(true)       // infinite loop:
  {
    motor[RightMotor] = (rand() % (max-min)) + min; // set 'rightMotor' to a random number in the range: [min, max]
    motor[LeftMotor]  = (rand() % (max-min)) + min; // set 'leftMotor' to a random number in the range: [min, max]
    wait1Msec(500); // wait 500 milliseconds
  }
}
