
#pragma config(Sensor, S3,     Sonic,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          Right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void forward(int speed)
{
	while(SensorValue(Sonic) > 5)
	{
		setMotorSyncTime(Left, Right, 0, 0, speed);
	}
}

void rev()
{
	motor[Right] = -50;
	motor[Left] = -50;
	sleep(1000);
}

task main()
{
	int battery=getBatteryVoltage();
	int r=-1;
	while(r<0)
		r=rand()%100 +1;


		displayBigTextLine(4,"Speed: %d",r);
		displayBigTextLine(6,"Battery: %d",battery);
	  sleep(3000);



	forward(r);
	rev();


	/*setMotorSyncTime(motorA, motorD, 0, 1000, r);
	sleep(1000);*/
}
